// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq7GOkS9NznWME_P15Ir2K38WD--Z_8eU',
    appId: '1:162499372255:web:10f3681ce32a4dcb33356a',
    messagingSenderId: '162499372255',
    projectId: 'database-caseddu',
    authDomain: 'database-caseddu.firebaseapp.com',
    storageBucket: 'database-caseddu.appspot.com',
    measurementId: 'G-5NTV3E7Z95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPbfiLumMibgrjJGTlKbua_kqhNcd1CaU',
    appId: '1:162499372255:android:6cc4c5101b770dbd33356a',
    messagingSenderId: '162499372255',
    projectId: 'database-caseddu',
    storageBucket: 'database-caseddu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMAN5cakanFgzMG3PdpO-jdTgO5rP1_38',
    appId: '1:162499372255:ios:9f20218c81ed7a2233356a',
    messagingSenderId: '162499372255',
    projectId: 'database-caseddu',
    storageBucket: 'database-caseddu.appspot.com',
    iosClientId: '162499372255-otuhmaoutrtndu385c2n4rdb8vpmc9oo.apps.googleusercontent.com',
    iosBundleId: 'com.forcompagnie.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMAN5cakanFgzMG3PdpO-jdTgO5rP1_38',
    appId: '1:162499372255:ios:49152d29c5a9dcbb33356a',
    messagingSenderId: '162499372255',
    projectId: 'database-caseddu',
    storageBucket: 'database-caseddu.appspot.com',
    iosClientId: '162499372255-a9k8ce0gh15odi473s120oocthcmo197.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
